use crate::output::{bold, dim, green, red, yellow};
use crate::plugin::builtin::health_config::{self, HealthConfig};
use std::path::Path;
use std::process::Command;

// ── Public entry point ──────────────────────────────────────────────

pub fn run(repo_root: &Path, args: &[&str]) {
    let subcommand = args.first().copied().filter(|a| !a.starts_with('-'));

    if args.iter().any(|a| *a == "--help" || *a == "-h") {
        if subcommand.is_none() {
            print_help();
        }
        return;
    }

    match subcommand {
        Some("init") => cmd_init(repo_root),
        Some("export") => cmd_export(repo_root),
        Some(other) => {
            eprintln!("Unknown health subcommand: {other}");
            eprintln!("Run `repo health --help` for usage.");
        }
        None => {
            let verbose = args.iter().any(|a| *a == "--verbose" || *a == "-v");
            let check_updates = args.iter().any(|a| *a == "--check-updates" || *a == "-u");
            cmd_check(repo_root, verbose, check_updates);
        }
    }
}

// ── init: write blank template ──────────────────────────────────────

fn cmd_init(repo_root: &Path) {
    let path = repo_root.join(".repo").join("health.toml");
    if path.exists() {
        eprintln!("  {} .repo/health.toml already exists", yellow("!!"));
        eprintln!("  Use `repo health export` to overwrite with current state,");
        eprintln!("  or edit the file directly.");
        return;
    }

    let template = health_config::blank_template();
    if let Err(e) = std::fs::write(&path, template) {
        eprintln!("Error writing {}: {e}", path.display());
        std::process::exit(1);
    }

    println!("  {} wrote .repo/health.toml", green("ok"));
    println!("  Edit the file to specify required tools and versions.");
}

// ── export: snapshot current env ────────────────────────────────────

fn cmd_export(repo_root: &Path) {
    let checks = default_checks();
    let mut found: Vec<(String, Option<String>)> = Vec::new();

    for check in &checks {
        let result = check.execute();
        if let CheckResult::Ok(version) = result {
            found.push((check.name.clone(), Some(version)));
        }
    }

    let cage = cage_name(&detect_cage());
    let config = health_config::snapshot_current(&found, cage);
    let toml_str = config.to_toml();

    let path = repo_root.join(".repo").join("health.toml");

    // Add a header comment.
    let content = format!(
        "# .repo/health.toml — Exported from current environment\n\
         # Generated by `repo health export`\n\
         # Edit as needed, then run `repo health` to validate.\n\n\
         {toml_str}"
    );

    if let Err(e) = std::fs::write(&path, &content) {
        eprintln!("Error writing {}: {e}", path.display());
        std::process::exit(1);
    }

    println!("  {} wrote .repo/health.toml", green("ok"));
    println!();
    print!("{content}");
}

// ── check: main health check ────────────────────────────────────────

fn cmd_check(repo_root: &Path, verbose: bool, check_updates: bool) {
    let health_cfg = HealthConfig::load(repo_root);
    let has_config = health_cfg.is_some();

    println!("{}", bold("Environment health check"));
    if has_config {
        println!("  {}", dim("validating against .repo/health.toml"));
    }
    if check_updates {
        println!("  {}", dim("checking for available updates..."));
    }
    println!();

    let mut pass = 0u32;
    let mut warn = 0u32;
    let mut fail = 0u32;

    let checks = default_checks();

    let w_name = checks
        .iter()
        .map(|c| c.name.len())
        .max()
        .unwrap_or(0)
        .max(9); // "toolchain"

    // ── Tool version checks ─────────────────────────────────────
    for check in &checks {
        let result = check.execute();
        match &result {
            CheckResult::Ok(version) => {
                // Validate against config if present.
                let constraint_msg = if let Some(cfg) = &health_cfg {
                    validate_tool_version(&check.name, version, cfg)
                } else {
                    None
                };

                if let Some(msg) = constraint_msg {
                    println!(
                        "  {} {:<w_name$}  {}  {}",
                        red("!!"),
                        check.name,
                        dim(version),
                        red(&msg),
                    );
                    print_tool_hint(&check.name, health_cfg.as_ref(), w_name);
                    fail += 1;
                } else {
                    // Check for available updates.
                    let update_msg = if check_updates {
                        check_for_update(&check.name, version, health_cfg.as_ref())
                    } else {
                        None
                    };

                    if let Some(latest) = update_msg {
                        println!(
                            "  {} {:<w_name$}  {}  {}",
                            yellow("~~"),
                            check.name,
                            dim(version),
                            yellow(&format!("update available: {latest}")),
                        );
                        warn += 1;
                    } else {
                        println!(
                            "  {} {:<w_name$}  {}",
                            green("ok"),
                            check.name,
                            dim(version),
                        );
                        pass += 1;
                    }
                }
            }
            CheckResult::Missing => {
                let required = health_cfg
                    .as_ref()
                    .and_then(|cfg| cfg.tools.get(&check.name))
                    .is_some_and(|t| t.required);

                if required {
                    println!(
                        "  {} {:<w_name$}  {}",
                        red("!!"),
                        check.name,
                        red("required but not found"),
                    );
                    print_tool_hint(&check.name, health_cfg.as_ref(), w_name);
                    fail += 1;
                } else if verbose {
                    println!(
                        "  {} {:<w_name$}  {}",
                        dim("--"),
                        dim(&check.name),
                        dim("not found"),
                    );
                }
            }
            CheckResult::Error(msg) => {
                println!("  {} {:<w_name$}  {}", red("!!"), check.name, yellow(msg),);
                fail += 1;
            }
        }
    }

    // Check for tools in config that aren't in the default list.
    if let Some(cfg) = &health_cfg {
        let known_names: Vec<&str> = checks.iter().map(|c| c.name.as_str()).collect();
        for (name, req) in &cfg.tools {
            if known_names.contains(&name.as_str()) {
                continue;
            }
            // Custom tool from config — probe it.
            let cmd = req.command.as_deref().unwrap_or(name.as_str());
            let args: Vec<&str> = req
                .version_args
                .as_ref()
                .map(|a| a.iter().map(|s| s.as_str()).collect())
                .unwrap_or_else(|| vec!["--version"]);

            let custom_check = Check::tool(cmd, &args, parse_first_line).display_name(name);
            let result = custom_check.execute();

            match &result {
                CheckResult::Ok(version) => {
                    let constraint_msg = validate_tool_version(name, version, cfg);
                    if let Some(msg) = constraint_msg {
                        println!(
                            "  {} {:<w_name$}  {}  {}",
                            red("!!"),
                            name,
                            dim(version),
                            red(&msg),
                        );
                        print_tool_hint(name, Some(cfg), w_name);
                        fail += 1;
                    } else {
                        let update_msg = if check_updates {
                            check_for_update(name, version, Some(cfg))
                        } else {
                            None
                        };

                        if let Some(latest) = update_msg {
                            println!(
                                "  {} {:<w_name$}  {}  {}",
                                yellow("~~"),
                                name,
                                dim(version),
                                yellow(&format!("update available: {latest}")),
                            );
                            warn += 1;
                        } else {
                            println!("  {} {:<w_name$}  {}", green("ok"), name, dim(version),);
                            pass += 1;
                        }
                    }
                }
                CheckResult::Missing if req.required => {
                    println!(
                        "  {} {:<w_name$}  {}",
                        red("!!"),
                        name,
                        red("required but not found"),
                    );
                    print_tool_hint(name, Some(cfg), w_name);
                    fail += 1;
                }
                CheckResult::Missing => {
                    if verbose {
                        println!(
                            "  {} {:<w_name$}  {}",
                            dim("--"),
                            dim(name),
                            dim("not found"),
                        );
                    }
                }
                CheckResult::Error(msg) => {
                    println!("  {} {:<w_name$}  {}", red("!!"), name, yellow(msg),);
                    fail += 1;
                }
            }
        }
    }

    // ── Repo-specific checks ────────────────────────────────────
    println!();
    println!("{}", bold("Repository"));
    println!();

    match run_cmd("git", &["branch", "--show-current"]) {
        Some(branch) => {
            println!("  {} {:<w_name$}  {}", green("ok"), "branch", dim(&branch));
            pass += 1;
        }
        None => {
            println!(
                "  {} {:<w_name$}  {}",
                red("!!"),
                "branch",
                yellow("not a git repository"),
            );
            fail += 1;
        }
    }

    let config_path = repo_root.join(".repo").join("config.toml");
    if config_path.is_file() {
        println!(
            "  {} {:<w_name$}  {}",
            green("ok"),
            "config",
            dim(".repo/config.toml"),
        );
        pass += 1;
    } else {
        println!(
            "  {} {:<w_name$}  {}",
            yellow("--"),
            "config",
            dim("no .repo/config.toml"),
        );
        warn += 1;
    }

    let health_path = repo_root.join(".repo").join("health.toml");
    if health_path.is_file() {
        println!(
            "  {} {:<w_name$}  {}",
            green("ok"),
            "health",
            dim(".repo/health.toml"),
        );
        pass += 1;
    } else {
        println!(
            "  {} {:<w_name$}  {}",
            dim("--"),
            "health",
            dim("no .repo/health.toml (run `repo health init`)"),
        );
    }

    let docs_root = repo_root.join("_docs");
    if docs_root.is_dir() {
        let subdirs: Vec<&str> = ["plans", "designs", "adrs", "references"]
            .iter()
            .filter(|d| docs_root.join(d).is_dir())
            .copied()
            .collect();
        println!(
            "  {} {:<w_name$}  {}",
            green("ok"),
            "_docs",
            dim(&subdirs.join(", ")),
        );
        pass += 1;
    } else {
        println!(
            "  {} {:<w_name$}  {}",
            yellow("--"),
            "_docs",
            dim("not found"),
        );
        warn += 1;
    }

    check_virtualenv(w_name, &mut pass, &mut warn);

    if let Some(toolchain) = run_cmd("rustup", &["show", "active-toolchain"]) {
        let short = toolchain.split_whitespace().next().unwrap_or(&toolchain);
        println!("  {} {:<w_name$}  {}", green("ok"), "toolchain", dim(short),);
        pass += 1;
    }

    // ── Environment / cage detection ────────────────────────────
    println!();
    println!("{}", bold("Environment"));
    println!();

    let cage = detect_cage();
    let cage_str = cage_name(&cage);

    // Validate cage against config.
    let cage_ok = if let Some(cfg) = &health_cfg {
        if cfg.environment.allowed_runtimes.is_empty() {
            true
        } else {
            cfg.environment
                .allowed_runtimes
                .iter()
                .any(|r| r == cage_str)
        }
    } else {
        true
    };

    if cage_ok {
        let label = match cage {
            Cage::Host => "bare host".to_string(),
            _ => cage_str.to_string(),
        };
        println!("  {} {:<w_name$}  {}", green("ok"), "runtime", label);
        pass += 1;
    } else {
        println!(
            "  {} {:<w_name$}  {}",
            red("!!"),
            "runtime",
            red(&format!(
                "{cage_str} (allowed: {})",
                health_cfg
                    .as_ref()
                    .unwrap()
                    .environment
                    .allowed_runtimes
                    .join(", ")
            )),
        );
        fail += 1;
    }

    // Privilege escalation.
    let privilege = detect_privilege();
    if let Some(cfg) = &health_cfg {
        let expected = &cfg.environment.privilege;
        if expected != "auto" && expected != &privilege {
            println!(
                "  {} {:<w_name$}  {}",
                red("!!"),
                "privilege",
                red(&format!("found {privilege}, expected {expected}")),
            );
            fail += 1;
        } else {
            println!(
                "  {} {:<w_name$}  {}",
                green("ok"),
                "privilege",
                dim(&privilege),
            );
            pass += 1;
        }
    } else {
        println!(
            "  {} {:<w_name$}  {}",
            green("ok"),
            "privilege",
            dim(&privilege),
        );
        pass += 1;
    }

    // Available shells.
    let shells = detect_shells();
    if shells.is_empty() {
        println!(
            "  {} {:<w_name$}  {}",
            yellow("--"),
            "shells",
            dim("none found in /etc/shells"),
        );
    } else {
        // Validate required shell.
        let shell_ok = if let Some(cfg) = &health_cfg {
            if let Some(ref required) = cfg.environment.required_shell {
                shells.iter().any(|s| s == required)
            } else {
                true
            }
        } else {
            true
        };

        if shell_ok {
            println!(
                "  {} {:<w_name$}  {}",
                green("ok"),
                "shells",
                dim(&shells.join(", ")),
            );
            pass += 1;
        } else {
            let required = &health_cfg
                .as_ref()
                .unwrap()
                .environment
                .required_shell
                .as_ref()
                .unwrap();
            println!(
                "  {} {:<w_name$}  {}",
                red("!!"),
                "shells",
                red(&format!(
                    "required shell '{required}' not in: {}",
                    shells.join(", ")
                )),
            );
            fail += 1;
        }
    }

    if let Ok(shell) = std::env::var("SHELL") {
        let short = Path::new(&shell)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        println!("  {} {:<w_name$}  {}", green("ok"), "default", dim(&short),);
    }

    // ── Custom checks ────────────────────────────────────────────
    if let Some(cfg) = &health_cfg
        && !cfg.checks.is_empty()
    {
        println!();
        println!("{}", bold("Checks"));
        println!();

        for (name, check) in &cfg.checks {
            let output = Command::new("sh").arg("-c").arg(&check.command).output();

            match output {
                Ok(out) if out.status.success() => {
                    println!(
                        "  {} {:<w_name$}  {}",
                        green("ok"),
                        name,
                        dim(&check.description),
                    );
                    pass += 1;
                }
                Ok(out) => {
                    let is_warn = check.severity == "warning";
                    let icon = if is_warn { yellow("--") } else { red("!!") };
                    let msg = if is_warn {
                        yellow(&check.description)
                    } else {
                        red(&check.description)
                    };

                    println!("  {} {:<w_name$}  {}", icon, name, msg);

                    let stderr = String::from_utf8_lossy(&out.stderr);
                    let stdout = String::from_utf8_lossy(&out.stdout);
                    let detail = if !stderr.trim().is_empty() {
                        stderr.trim().lines().next().unwrap_or("")
                    } else if !stdout.trim().is_empty() {
                        stdout.trim().lines().next().unwrap_or("")
                    } else {
                        ""
                    };
                    if !detail.is_empty() {
                        println!("    {:<w_name$}  {}", "", dim(detail));
                    }

                    if let Some(ref hint) = check.hint {
                        println!("    {:<w_name$}  {}", "", dim(&format!("hint: {hint}")));
                    }

                    if is_warn {
                        warn += 1;
                    } else {
                        fail += 1;
                    }
                }
                Err(e) => {
                    println!(
                        "  {} {:<w_name$}  {}",
                        red("!!"),
                        name,
                        red(&format!("failed to run: {e}")),
                    );
                    fail += 1;
                }
            }
        }
    }

    // ── Summary ─────────────────────────────────────────────────
    println!();
    println!(
        "  {} passed, {} warnings, {} errors",
        green(&pass.to_string()),
        yellow(&warn.to_string()),
        if fail > 0 {
            red(&fail.to_string())
        } else {
            fail.to_string()
        },
    );

    if fail > 0 {
        std::process::exit(1);
    }
}

// ── Help ────────────────────────────────────────────────────────────

fn print_help() {
    println!(
        "\
repo health — Check development environment

USAGE:
    repo health [COMMAND] [OPTIONS]

COMMANDS:
    init        Create a blank .repo/health.toml template
    export      Snapshot current environment into .repo/health.toml

OPTIONS:
    -u, --check-updates  Check for available updates (queries package registries)
    -v, --verbose        Show missing (not-found) tools too
    -h, --help           Print this help message

When .repo/health.toml exists, `repo health` validates the environment
against it (required tools, version constraints, allowed runtimes,
privilege escalation method).

Without health.toml, it performs a best-effort scan of common tools.

With --check-updates, queries npm registry, rustup, etc. to detect
newer versions. Requires network access."
    );
}

// ── Update checking ─────────────────────────────────────────────────

fn check_for_update(name: &str, current_raw: &str, cfg: Option<&HealthConfig>) -> Option<String> {
    let latest = health_config::check_latest_version(name, cfg)?;
    let current = extract_version_number(current_raw);

    if current.is_empty() || latest.is_empty() {
        return None;
    }

    if compare_versions(&current, &latest) == std::cmp::Ordering::Less {
        Some(format!("{current} -> {latest}"))
    } else {
        None
    }
}

// ── Install / URL hints ─────────────────────────────────────────────

fn print_tool_hint(name: &str, cfg: Option<&HealthConfig>, w_name: usize) {
    let req = cfg.and_then(|c| c.tools.get(name));

    if let Some(install) = req.and_then(|r| r.install.as_deref()) {
        println!(
            "    {:<w_name$}  {}",
            "",
            dim(&format!("install: {install}")),
        );
    }

    if let Some(url) = req.and_then(|r| r.url.as_deref()) {
        println!("    {:<w_name$}  {}", "", dim(&format!("    url: {url}")),);
    }
}

// ── Version validation ──────────────────────────────────────────────

fn validate_tool_version(name: &str, raw_version: &str, cfg: &HealthConfig) -> Option<String> {
    let req = cfg.tools.get(name)?;

    let version = extract_version_number(raw_version);

    if let Some(ref exact) = req.exact_version
        && version != *exact
    {
        return Some(format!("expected {exact}, got {version}"));
    }

    if let Some(ref min) = req.min_version
        && compare_versions(&version, min) == std::cmp::Ordering::Less
    {
        return Some(format!("minimum {min}, got {version}"));
    }

    None
}

/// Compare dot-separated version strings numerically.
/// "1.70.0" vs "1.9.0" -> Greater (70 > 9).
fn compare_versions(a: &str, b: &str) -> std::cmp::Ordering {
    let parse = |s: &str| -> Vec<u64> {
        s.split('.')
            .map(|p| p.parse::<u64>().unwrap_or(0))
            .collect()
    };
    let va = parse(a);
    let vb = parse(b);
    let len = va.len().max(vb.len());
    for i in 0..len {
        let a = va.get(i).copied().unwrap_or(0);
        let b = vb.get(i).copied().unwrap_or(0);
        match a.cmp(&b) {
            std::cmp::Ordering::Equal => continue,
            ord => return ord,
        }
    }
    std::cmp::Ordering::Equal
}

/// Extract a semver-like version number from raw output.
fn extract_version_number(raw: &str) -> String {
    for word in raw.split_whitespace() {
        let word = word.strip_prefix('v').unwrap_or(word);
        if word.chars().next().is_some_and(|c| c.is_ascii_digit()) && word.contains('.') {
            let clean: String = word
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.')
                .collect();
            if clean.contains('.') {
                return clean;
            }
        }
    }
    String::new()
}

// ── Default check list ──────────────────────────────────────────────

fn default_checks() -> Vec<Check> {
    vec![
        Check::tool("git", &["--version"], parse_git),
        Check::tool("rustc", &["--version"], parse_first_line),
        Check::tool("cargo", &["--version"], parse_first_line),
        Check::tool("clippy-driver", &["--version"], parse_first_line).display_name("clippy"),
        Check::tool("rustfmt", &["--version"], parse_first_line),
        Check::tool("node", &["--version"], parse_first_line),
        Check::tool("npm", &["--version"], parse_npm),
        Check::tool("pnpm", &["--version"], parse_pnpm),
        Check::tool("bun", &["--version"], parse_first_line),
        // Agent skills (npx skills)
        Check::tool("npx", &["skills", "--version"], parse_first_line).display_name("skills"),
        // Python
        Check::tool("python3", &["--version"], parse_first_line).display_name("python"),
        Check::tool("pip3", &["--version"], parse_pip),
        Check::tool("uv", &["--version"], parse_first_line),
        Check::tool("docker", &["--version"], parse_first_line),
        Check::tool("make", &["--version"], parse_first_line),
        Check::tool("cmake", &["--version"], parse_first_line),
        Check::tool("go", &["version"], parse_go),
        Check::tool("java", &["-version"], parse_first_line),
        Check::tool("zsh", &["--version"], parse_first_line),
        Check::tool("bash", &["--version"], parse_bash),
    ]
}

// ── Check model ─────────────────────────────────────────────────────

type Parser = fn(&str) -> String;

struct Check {
    name: String,
    cmd: String,
    args: Vec<String>,
    parser: Parser,
}

enum CheckResult {
    Ok(String),
    Missing,
    Error(String),
}

impl Check {
    fn tool(cmd: &str, args: &[&str], parser: Parser) -> Self {
        Self {
            name: cmd.to_string(),
            cmd: cmd.to_string(),
            args: args.iter().map(|s| (*s).to_string()).collect(),
            parser,
        }
    }

    fn display_name(mut self, name: &str) -> Self {
        self.name = name.to_string();
        self
    }

    fn execute(&self) -> CheckResult {
        let output = Command::new(&self.cmd).args(&self.args).output();

        match output {
            Ok(out) if out.status.success() => {
                let raw = String::from_utf8_lossy(&out.stdout);
                let raw = if raw.trim().is_empty() {
                    String::from_utf8_lossy(&out.stderr).into_owned()
                } else {
                    raw.into_owned()
                };
                let version = (self.parser)(&raw);
                CheckResult::Ok(version)
            }
            Ok(out) => {
                let raw = String::from_utf8_lossy(&out.stderr);
                if raw.trim().is_empty() {
                    CheckResult::Error(format!("exited with {}", out.status))
                } else {
                    let version = (self.parser)(&raw);
                    if version.is_empty() {
                        CheckResult::Error(format!("exited with {}", out.status))
                    } else {
                        CheckResult::Ok(version)
                    }
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => CheckResult::Missing,
            Err(e) => CheckResult::Error(e.to_string()),
        }
    }
}

// ── Parsers ─────────────────────────────────────────────────────────

fn parse_first_line(raw: &str) -> String {
    raw.lines().next().unwrap_or("").trim().to_string()
}

fn parse_git(raw: &str) -> String {
    raw.trim()
        .strip_prefix("git version ")
        .unwrap_or(raw.trim())
        .to_string()
}

fn parse_npm(raw: &str) -> String {
    format!("npm {}", raw.trim())
}

fn parse_pnpm(raw: &str) -> String {
    format!("pnpm {}", raw.trim())
}

fn parse_pip(raw: &str) -> String {
    let line = raw.lines().next().unwrap_or("").trim();
    if let Some(idx) = line.find(" from ")
        && let Some(paren) = line.rfind('(')
    {
        return format!("{} {}", &line[..idx], &line[paren..]);
    }
    line.to_string()
}

fn parse_go(raw: &str) -> String {
    raw.split_whitespace()
        .nth(2)
        .unwrap_or(raw.trim())
        .to_string()
}

fn parse_bash(raw: &str) -> String {
    raw.lines().next().unwrap_or("").trim().to_string()
}

// ── Helpers ─────────────────────────────────────────────────────────

fn run_cmd(cmd: &str, args: &[&str]) -> Option<String> {
    Command::new(cmd)
        .args(args)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
}

fn check_virtualenv(w_name: usize, pass: &mut u32, warn: &mut u32) {
    if let Ok(venv) = std::env::var("VIRTUAL_ENV") {
        let short = Path::new(&venv)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy();
        println!(
            "  {} {:<w_name$}  {}",
            green("ok"),
            "venv",
            dim(&format!("{short} (active)")),
        );
        *pass += 1;
        return;
    }

    if let Ok(env) = std::env::var("CONDA_DEFAULT_ENV") {
        println!(
            "  {} {:<w_name$}  {}",
            green("ok"),
            "venv",
            dim(&format!("conda: {env}")),
        );
        *pass += 1;
        return;
    }

    if Path::new(".venv").is_dir() || Path::new("venv").is_dir() {
        println!(
            "  {} {:<w_name$}  {}",
            yellow("--"),
            "venv",
            dim("found but not activated"),
        );
        *warn += 1;
    }
}

fn detect_privilege() -> String {
    if which_exists("sudo") {
        "sudo".into()
    } else if which_exists("doas") {
        "doas".into()
    } else if which_exists("pkexec") {
        "pkexec".into()
    } else {
        "none".into()
    }
}

fn which_exists(cmd: &str) -> bool {
    Command::new("which")
        .arg(cmd)
        .output()
        .is_ok_and(|o| o.status.success())
}

// ── Cage / container detection ──────────────────────────────────────

enum Cage {
    Docker,
    Podman,
    Lxc,
    Wsl,
    Kubernetes,
    Host,
}

fn cage_name(cage: &Cage) -> &'static str {
    match cage {
        Cage::Docker => "docker",
        Cage::Podman => "podman",
        Cage::Lxc => "lxc",
        Cage::Wsl => "wsl",
        Cage::Kubernetes => "kubernetes",
        Cage::Host => "host",
    }
}

fn detect_cage() -> Cage {
    if Path::new("/var/run/secrets/kubernetes.io").exists() {
        return Cage::Kubernetes;
    }
    if Path::new("/.dockerenv").exists() {
        return Cage::Docker;
    }
    if Path::new("/run/.containerenv").exists() {
        return Cage::Podman;
    }
    if let Ok(cgroup) = std::fs::read_to_string("/proc/1/cgroup") {
        let cg = cgroup.to_lowercase();
        if cg.contains("docker") {
            return Cage::Docker;
        }
        if cg.contains("kubepods") {
            return Cage::Kubernetes;
        }
        if cg.contains("lxc") {
            return Cage::Lxc;
        }
    }
    if let Ok(val) = std::env::var("container") {
        return match val.as_str() {
            "docker" => Cage::Docker,
            "podman" => Cage::Podman,
            "lxc" => Cage::Lxc,
            _ => Cage::Docker,
        };
    }
    if let Ok(version) = std::fs::read_to_string("/proc/version")
        && (version.contains("microsoft") || version.contains("Microsoft"))
    {
        return Cage::Wsl;
    }
    Cage::Host
}

// ── Available shells ────────────────────────────────────────────────

fn detect_shells() -> Vec<String> {
    let content = match std::fs::read_to_string("/etc/shells") {
        Ok(c) => c,
        Err(_) => return Vec::new(),
    };

    let mut shells: Vec<String> = content
        .lines()
        .filter(|l| {
            let l = l.trim();
            !l.is_empty() && !l.starts_with('#') && l.starts_with('/')
        })
        .filter_map(|l| {
            Path::new(l.trim())
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
        })
        .collect();

    shells.sort();
    shells.dedup();
    shells
}
