use crate::output::{bold, dim, green, red, yellow};
use crate::plugin::builtin::health_config::{self, HealthConfig};
use serde::Serialize;
use std::path::Path;
use std::process::Command;

#[derive(Debug, Serialize)]
struct HealthReport {
    passed: u32,
    warnings: u32,
    errors: u32,
    sections: Vec<HealthSection>,
}

#[derive(Debug, Serialize)]
struct HealthSection {
    name: String,
    checks: Vec<HealthCheckRecord>,
}

#[derive(Debug, Serialize)]
struct HealthCheckRecord {
    name: String,
    status: String,
    summary: String,
    details: Vec<String>,
}

// ── Public entry point ──────────────────────────────────────────────

pub fn run(repo_root: &Path, args: &[&str]) {
    let subcommand = args.first().copied().filter(|a| !a.starts_with('-'));
    let json = args.contains(&"--json");

    if args.iter().any(|a| *a == "--help" || *a == "-h") {
        if subcommand.is_none() {
            print_help();
        }
        return;
    }

    match subcommand {
        Some("init") => cmd_init(repo_root),
        Some("export") => cmd_export(repo_root),
        Some(other) => {
            eprintln!("Unknown health subcommand: {other}");
            eprintln!("Run `repo health --help` for usage.");
        }
        None => {
            let verbose = args.iter().any(|a| *a == "--verbose" || *a == "-v");
            let check_updates = args.iter().any(|a| *a == "--check-updates" || *a == "-u");
            cmd_check(repo_root, verbose, check_updates, json);
        }
    }
}

// ── init: write blank template ──────────────────────────────────────

fn cmd_init(repo_root: &Path) {
    let path = repo_root.join(".repo").join("health.toml");
    if path.exists() {
        eprintln!("  {} .repo/health.toml already exists", yellow("!!"));
        eprintln!("  Use `repo health export` to overwrite with current state,");
        eprintln!("  or edit the file directly.");
        return;
    }

    let template = health_config::blank_template();
    if let Err(e) = std::fs::write(&path, template) {
        eprintln!("Error writing {}: {e}", path.display());
        std::process::exit(1);
    }

    println!("  {} wrote .repo/health.toml", green("ok"));
    println!("  Edit the file to specify required tools and versions.");
}

// ── export: snapshot current env ────────────────────────────────────

fn cmd_export(repo_root: &Path) {
    let checks = default_checks();
    let mut found: Vec<(String, Option<String>)> = Vec::new();

    for check in &checks {
        let result = check.execute();
        if let CheckResult::Ok(version) = result {
            found.push((check.name.clone(), Some(version)));
        }
    }

    let cage = cage_name(&detect_cage());
    let config = health_config::snapshot_current(&found, cage);
    let toml_str = config.to_toml();

    let path = repo_root.join(".repo").join("health.toml");

    // Add a header comment.
    let content = format!(
        "# .repo/health.toml — Exported from current environment\n\
         # Generated by `repo health export`\n\
         # Edit as needed, then run `repo health` to validate.\n\n\
         {toml_str}"
    );

    if let Err(e) = std::fs::write(&path, &content) {
        eprintln!("Error writing {}: {e}", path.display());
        std::process::exit(1);
    }

    println!("  {} wrote .repo/health.toml", green("ok"));
    println!();
    print!("{content}");
}

// ── check: main health check ────────────────────────────────────────

fn cmd_check(repo_root: &Path, verbose: bool, check_updates: bool, json: bool) {
    let report = build_report(repo_root, verbose, check_updates);

    if json {
        println!(
            "{}",
            serde_json::to_string_pretty(&report).unwrap_or_else(|_| "{}".to_string())
        );
    } else {
        print_report(&report);
    }

    if report.errors > 0 {
        std::process::exit(1);
    }
}

#[expect(clippy::too_many_lines)]
fn build_report(repo_root: &Path, verbose: bool, check_updates: bool) -> HealthReport {
    let health_cfg = HealthConfig::load(repo_root);

    let mut pass = 0u32;
    let mut warn = 0u32;
    let mut fail = 0u32;
    let mut tool_checks = Vec::new();
    let mut repo_checks = Vec::new();
    let mut env_checks = Vec::new();
    let mut custom_checks = Vec::new();

    let checks = default_checks();

    // ── Tool version checks ─────────────────────────────────────
    for check in &checks {
        let result = check.execute();
        match &result {
            CheckResult::Ok(version) => {
                let constraint_msg = if let Some(cfg) = &health_cfg {
                    validate_tool_version(&check.name, version, cfg)
                } else {
                    None
                };

                if let Some(msg) = constraint_msg {
                    let mut details = Vec::new();
                    append_tool_hint_details(&mut details, &check.name, health_cfg.as_ref());
                    tool_checks.push(HealthCheckRecord {
                        name: check.name.clone(),
                        status: "error".into(),
                        summary: format!("{version} ({msg})"),
                        details,
                    });
                    fail += 1;
                } else {
                    let update_msg = if check_updates {
                        check_for_update(&check.name, version, health_cfg.as_ref())
                    } else {
                        None
                    };

                    if let Some(latest) = update_msg {
                        tool_checks.push(HealthCheckRecord {
                            name: check.name.clone(),
                            status: "warning".into(),
                            summary: format!("{version} (update available: {latest})"),
                            details: Vec::new(),
                        });
                        warn += 1;
                    } else {
                        tool_checks.push(HealthCheckRecord {
                            name: check.name.clone(),
                            status: "ok".into(),
                            summary: version.clone(),
                            details: Vec::new(),
                        });
                        pass += 1;
                    }
                }
            }
            CheckResult::Missing => {
                let required = health_cfg
                    .as_ref()
                    .and_then(|cfg| cfg.tools.get(&check.name))
                    .is_some_and(|t| t.required);

                if required {
                    let mut details = Vec::new();
                    append_tool_hint_details(&mut details, &check.name, health_cfg.as_ref());
                    tool_checks.push(HealthCheckRecord {
                        name: check.name.clone(),
                        status: "error".into(),
                        summary: "required but not found".into(),
                        details,
                    });
                    fail += 1;
                } else if verbose {
                    tool_checks.push(HealthCheckRecord {
                        name: check.name.clone(),
                        status: "info".into(),
                        summary: "not found".into(),
                        details: Vec::new(),
                    });
                }
            }
            CheckResult::Error(msg) => {
                tool_checks.push(HealthCheckRecord {
                    name: check.name.clone(),
                    status: "error".into(),
                    summary: msg.clone(),
                    details: Vec::new(),
                });
                fail += 1;
            }
        }
    }

    // Check for tools in config that aren't in the default list.
    if let Some(cfg) = &health_cfg {
        let known_names: Vec<&str> = checks.iter().map(|c| c.name.as_str()).collect();
        for (name, req) in &cfg.tools {
            if known_names.contains(&name.as_str()) {
                continue;
            }
            // Custom tool from config — probe it.
            let cmd = req.command.as_deref().unwrap_or(name.as_str());
            let args: Vec<&str> = req
                .version_args
                .as_ref()
                .map_or_else(|| vec!["--version"], |a| {
                    a.iter().map(String::as_str).collect()
                });

            let custom_check = Check::tool(cmd, &args, parse_first_line).display_name(name);
            let result = custom_check.execute();

            match &result {
                CheckResult::Ok(version) => {
                    let constraint_msg = validate_tool_version(name, version, cfg);
                    if let Some(msg) = constraint_msg {
                        let mut details = Vec::new();
                        append_tool_hint_details(&mut details, name, Some(cfg));
                        tool_checks.push(HealthCheckRecord {
                            name: name.clone(),
                            status: "error".into(),
                            summary: format!("{version} ({msg})"),
                            details,
                        });
                        fail += 1;
                    } else {
                        let update_msg = if check_updates {
                            check_for_update(name, version, Some(cfg))
                        } else {
                            None
                        };

                        if let Some(latest) = update_msg {
                            tool_checks.push(HealthCheckRecord {
                                name: name.clone(),
                                status: "warning".into(),
                                summary: format!("{version} (update available: {latest})"),
                                details: Vec::new(),
                            });
                            warn += 1;
                        } else {
                            tool_checks.push(HealthCheckRecord {
                                name: name.clone(),
                                status: "ok".into(),
                                summary: version.clone(),
                                details: Vec::new(),
                            });
                            pass += 1;
                        }
                    }
                }
                CheckResult::Missing if req.required => {
                    let mut details = Vec::new();
                    append_tool_hint_details(&mut details, name, Some(cfg));
                    tool_checks.push(HealthCheckRecord {
                        name: name.clone(),
                        status: "error".into(),
                        summary: "required but not found".into(),
                        details,
                    });
                    fail += 1;
                }
                CheckResult::Missing => {
                    if verbose {
                        tool_checks.push(HealthCheckRecord {
                            name: name.clone(),
                            status: "info".into(),
                            summary: "not found".into(),
                            details: Vec::new(),
                        });
                    }
                }
                CheckResult::Error(msg) => {
                    tool_checks.push(HealthCheckRecord {
                        name: name.clone(),
                        status: "error".into(),
                        summary: msg.clone(),
                        details: Vec::new(),
                    });
                    fail += 1;
                }
            }
        }
    }

    // ── Repo-specific checks ────────────────────────────────────
    if let Some(branch) = run_cmd("git", &["branch", "--show-current"]) {
        repo_checks.push(HealthCheckRecord {
            name: "branch".into(),
            status: "ok".into(),
            summary: branch,
            details: Vec::new(),
        });
        pass += 1;
    } else {
        repo_checks.push(HealthCheckRecord {
            name: "branch".into(),
            status: "error".into(),
            summary: "not a git repository".into(),
            details: Vec::new(),
        });
        fail += 1;
    }

    let config_path = repo_root.join(".repo").join("config.toml");
    if config_path.is_file() {
        repo_checks.push(HealthCheckRecord {
            name: "config".into(),
            status: "ok".into(),
            summary: ".repo/config.toml".into(),
            details: Vec::new(),
        });
        pass += 1;
    } else {
        repo_checks.push(HealthCheckRecord {
            name: "config".into(),
            status: "warning".into(),
            summary: "no .repo/config.toml".into(),
            details: Vec::new(),
        });
        warn += 1;
    }

    let health_path = repo_root.join(".repo").join("health.toml");
    if health_path.is_file() {
        repo_checks.push(HealthCheckRecord {
            name: "health".into(),
            status: "ok".into(),
            summary: ".repo/health.toml".into(),
            details: Vec::new(),
        });
        pass += 1;
    } else {
        repo_checks.push(HealthCheckRecord {
            name: "health".into(),
            status: "info".into(),
            summary: "no .repo/health.toml (run `repo health init`)".into(),
            details: Vec::new(),
        });
    }

    let docs_root = repo_root.join("_docs");
    if docs_root.is_dir() {
        let subdirs: Vec<&str> = ["plans", "designs", "adrs", "references"]
            .iter()
            .filter(|d| docs_root.join(d).is_dir())
            .copied()
            .collect();
        repo_checks.push(HealthCheckRecord {
            name: "_docs".into(),
            status: "ok".into(),
            summary: subdirs.join(", "),
            details: Vec::new(),
        });
        pass += 1;
    } else {
        repo_checks.push(HealthCheckRecord {
            name: "_docs".into(),
            status: "warning".into(),
            summary: "not found".into(),
            details: Vec::new(),
        });
        warn += 1;
    }

    check_virtualenv(&mut env_checks, &mut pass, &mut warn);

    if let Some(toolchain) = run_cmd("rustup", &["show", "active-toolchain"]) {
        let short = toolchain.split_whitespace().next().unwrap_or(&toolchain);
        repo_checks.push(HealthCheckRecord {
            name: "toolchain".into(),
            status: "ok".into(),
            summary: short.into(),
            details: Vec::new(),
        });
        pass += 1;
    }

    // ── Environment / cage detection ────────────────────────────
    let cage = detect_cage();
    let cage_str = cage_name(&cage);

    // Validate cage against config.
    let cage_ok = if let Some(cfg) = &health_cfg {
        if cfg.environment.allowed_runtimes.is_empty() {
            true
        } else {
            cfg.environment
                .allowed_runtimes
                .iter()
                .any(|r| r == cage_str)
        }
    } else {
        true
    };

    if cage_ok {
        let label = match cage {
            Cage::Host => "bare host".to_string(),
            _ => cage_str.to_string(),
        };
        env_checks.push(HealthCheckRecord {
            name: "runtime".into(),
            status: "ok".into(),
            summary: label,
            details: Vec::new(),
        });
        pass += 1;
    } else {
        env_checks.push(HealthCheckRecord {
            name: "runtime".into(),
            status: "error".into(),
            summary: format!(
                "{cage_str} (allowed: {})",
                health_cfg
                    .as_ref()
                    .expect("checked above")
                    .environment
                    .allowed_runtimes
                    .join(", ")
            ),
            details: Vec::new(),
        });
        fail += 1;
    }

    // Privilege escalation.
    let privilege = detect_privilege();
    if let Some(cfg) = &health_cfg {
        let expected = &cfg.environment.privilege;
        if expected != "auto" && expected != &privilege {
            env_checks.push(HealthCheckRecord {
                name: "privilege".into(),
                status: "error".into(),
                summary: format!("found {privilege}, expected {expected}"),
                details: Vec::new(),
            });
            fail += 1;
        } else {
            env_checks.push(HealthCheckRecord {
                name: "privilege".into(),
                status: "ok".into(),
                summary: privilege,
                details: Vec::new(),
            });
            pass += 1;
        }
    } else {
        env_checks.push(HealthCheckRecord {
            name: "privilege".into(),
            status: "ok".into(),
            summary: privilege,
            details: Vec::new(),
        });
        pass += 1;
    }

    // Available shells.
    let shells = detect_shells();
    if shells.is_empty() {
        env_checks.push(HealthCheckRecord {
            name: "shells".into(),
            status: "warning".into(),
            summary: "none found in /etc/shells".into(),
            details: Vec::new(),
        });
    } else {
        // Validate required shell.
        let shell_ok = if let Some(cfg) = &health_cfg {
            if let Some(ref required) = cfg.environment.required_shell {
                shells.iter().any(|s| s == required)
            } else {
                true
            }
        } else {
            true
        };

        if shell_ok {
            env_checks.push(HealthCheckRecord {
                name: "shells".into(),
                status: "ok".into(),
                summary: shells.join(", "),
                details: Vec::new(),
            });
            pass += 1;
        } else {
            let required = &health_cfg
                .as_ref()
                .unwrap()
                .environment
                .required_shell
                .as_ref()
                .unwrap();
            env_checks.push(HealthCheckRecord {
                name: "shells".into(),
                status: "error".into(),
                summary: format!("required shell '{required}' not in: {}", shells.join(", ")),
                details: Vec::new(),
            });
            fail += 1;
        }
    }

    if let Ok(shell) = std::env::var("SHELL") {
        let short = Path::new(&shell)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        env_checks.push(HealthCheckRecord {
            name: "default".into(),
            status: "ok".into(),
            summary: short,
            details: Vec::new(),
        });
    }

    // ── Custom checks ────────────────────────────────────────────
    if let Some(cfg) = &health_cfg
        && !cfg.checks.is_empty()
    {
        for (name, check) in &cfg.checks {
            let output = Command::new("sh").arg("-c").arg(&check.command).output();

            match output {
                Ok(out) if out.status.success() => {
                    custom_checks.push(HealthCheckRecord {
                        name: name.clone(),
                        status: "ok".into(),
                        summary: check.description.clone(),
                        details: Vec::new(),
                    });
                    pass += 1;
                }
                Ok(out) => {
                    let is_warn = check.severity == "warning";

                    let stderr = String::from_utf8_lossy(&out.stderr);
                    let stdout = String::from_utf8_lossy(&out.stdout);
                    let detail = if !stderr.trim().is_empty() {
                        stderr.trim().lines().next().unwrap_or("")
                    } else if !stdout.trim().is_empty() {
                        stdout.trim().lines().next().unwrap_or("")
                    } else {
                        ""
                    };
                    let mut details = Vec::new();
                    if !detail.is_empty() {
                        details.push(detail.to_string());
                    }
                    if let Some(ref hint) = check.hint {
                        details.push(format!("hint: {hint}"));
                    }
                    custom_checks.push(HealthCheckRecord {
                        name: name.clone(),
                        status: if is_warn { "warning" } else { "error" }.into(),
                        summary: check.description.clone(),
                        details,
                    });

                    if is_warn {
                        warn += 1;
                    } else {
                        fail += 1;
                    }
                }
                Err(e) => {
                    custom_checks.push(HealthCheckRecord {
                        name: name.clone(),
                        status: "error".into(),
                        summary: format!("failed to run: {e}"),
                        details: Vec::new(),
                    });
                    fail += 1;
                }
            }
        }
    }

    let mut sections = vec![
        HealthSection {
            name: "Tools".into(),
            checks: tool_checks,
        },
        HealthSection {
            name: "Repository".into(),
            checks: repo_checks,
        },
        HealthSection {
            name: "Environment".into(),
            checks: env_checks,
        },
    ];
    if !custom_checks.is_empty() {
        sections.push(HealthSection {
            name: "Checks".into(),
            checks: custom_checks,
        });
    }

    HealthReport {
        passed: pass,
        warnings: warn,
        errors: fail,
        sections,
    }
}

// ── Help ────────────────────────────────────────────────────────────

fn print_help() {
    println!(
        "\
repo health — Check development environment

USAGE:
    repo health [COMMAND] [OPTIONS]

COMMANDS:
    init        Create a blank .repo/health.toml template
    export      Snapshot current environment into .repo/health.toml

OPTIONS:
    -u, --check-updates  Check for available updates (queries package registries)
    -v, --verbose        Show missing (not-found) tools too
    --json               Emit machine-readable JSON for `repo health`
    -h, --help           Print this help message

When .repo/health.toml exists, `repo health` validates the environment
against it (required tools, version constraints, allowed runtimes,
privilege escalation method).

Without health.toml, it performs a best-effort scan of common tools.

With --check-updates, queries npm registry, rustup, etc. to detect
newer versions. Requires network access."
    );
}

// ── Update checking ─────────────────────────────────────────────────

fn check_for_update(name: &str, current_raw: &str, cfg: Option<&HealthConfig>) -> Option<String> {
    let latest = health_config::check_latest_version(name, cfg)?;
    let current = extract_version_number(current_raw);

    if current.is_empty() || latest.is_empty() {
        return None;
    }

    if compare_versions(&current, &latest) == std::cmp::Ordering::Less {
        Some(format!("{current} -> {latest}"))
    } else {
        None
    }
}

// ── Install / URL hints ─────────────────────────────────────────────

fn append_tool_hint_details(details: &mut Vec<String>, name: &str, cfg: Option<&HealthConfig>) {
    let req = cfg.and_then(|c| c.tools.get(name));

    if let Some(install) = req.and_then(|r| r.install.as_deref()) {
        details.push(format!("install: {install}"));
    }

    if let Some(url) = req.and_then(|r| r.url.as_deref()) {
        details.push(format!("url: {url}"));
    }
}

// ── Version validation ──────────────────────────────────────────────

fn validate_tool_version(name: &str, raw_version: &str, cfg: &HealthConfig) -> Option<String> {
    let req = cfg.tools.get(name)?;

    let version = extract_version_number(raw_version);

    if let Some(ref exact) = req.exact_version
        && version != *exact
    {
        return Some(format!("expected {exact}, got {version}"));
    }

    if let Some(ref min) = req.min_version
        && compare_versions(&version, min) == std::cmp::Ordering::Less
    {
        return Some(format!("minimum {min}, got {version}"));
    }

    None
}

/// Compare dot-separated version strings numerically.
/// "1.70.0" vs "1.9.0" -> Greater (70 > 9).
fn compare_versions(a: &str, b: &str) -> std::cmp::Ordering {
    let parse = |s: &str| -> Vec<u64> {
        s.split('.')
            .map(|p| p.parse::<u64>().unwrap_or(0))
            .collect()
    };
    let va = parse(a);
    let vb = parse(b);
    let len = va.len().max(vb.len());
    for i in 0..len {
        let a = va.get(i).copied().unwrap_or(0);
        let b = vb.get(i).copied().unwrap_or(0);
        let ord = a.cmp(&b);
        if ord != std::cmp::Ordering::Equal {
            return ord;
        }
    }
    std::cmp::Ordering::Equal
}

/// Extract a semver-like version number from raw output.
fn extract_version_number(raw: &str) -> String {
    for word in raw.split_whitespace() {
        let word = word.strip_prefix('v').unwrap_or(word);
        if word.chars().next().is_some_and(|c| c.is_ascii_digit()) && word.contains('.') {
            let clean: String = word
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.')
                .collect();
            if clean.contains('.') {
                return clean;
            }
        }
    }
    String::new()
}

// ── Default check list ──────────────────────────────────────────────

fn default_checks() -> Vec<Check> {
    vec![
        Check::tool("git", &["--version"], parse_git),
        Check::tool("rustc", &["--version"], parse_first_line),
        Check::tool("cargo", &["--version"], parse_first_line),
        Check::tool("clippy-driver", &["--version"], parse_first_line).display_name("clippy"),
        Check::tool("rustfmt", &["--version"], parse_first_line),
        Check::tool("node", &["--version"], parse_first_line),
        Check::tool("npm", &["--version"], parse_npm),
        Check::tool("pnpm", &["--version"], parse_pnpm),
        Check::tool("bun", &["--version"], parse_first_line),
        // Agent skills (npx skills)
        Check::tool("npx", &["skills", "--version"], parse_first_line).display_name("skills"),
        // Python
        Check::tool("python3", &["--version"], parse_first_line).display_name("python"),
        Check::tool("pip3", &["--version"], parse_pip),
        Check::tool("uv", &["--version"], parse_first_line),
        Check::tool("docker", &["--version"], parse_first_line),
        Check::tool("make", &["--version"], parse_first_line),
        Check::tool("cmake", &["--version"], parse_first_line),
        Check::tool("go", &["version"], parse_go),
        Check::tool("java", &["-version"], parse_first_line),
        Check::tool("zsh", &["--version"], parse_first_line),
        Check::tool("bash", &["--version"], parse_bash),
    ]
}

// ── Check model ─────────────────────────────────────────────────────

type Parser = fn(&str) -> String;

struct Check {
    name: String,
    cmd: String,
    args: Vec<String>,
    parser: Parser,
}

enum CheckResult {
    Ok(String),
    Missing,
    Error(String),
}

impl Check {
    fn tool(cmd: &str, args: &[&str], parser: Parser) -> Self {
        Self {
            name: cmd.to_string(),
            cmd: cmd.to_string(),
            args: args.iter().map(|s| (*s).to_string()).collect(),
            parser,
        }
    }

    fn display_name(mut self, name: &str) -> Self {
        self.name = name.to_string();
        self
    }

    fn execute(&self) -> CheckResult {
        let output = Command::new(&self.cmd).args(&self.args).output();

        match output {
            Ok(out) if out.status.success() => {
                let raw = String::from_utf8_lossy(&out.stdout);
                let raw = if raw.trim().is_empty() {
                    String::from_utf8_lossy(&out.stderr).into_owned()
                } else {
                    raw.into_owned()
                };
                let version = (self.parser)(&raw);
                CheckResult::Ok(version)
            }
            Ok(out) => {
                let raw = String::from_utf8_lossy(&out.stderr);
                if raw.trim().is_empty() {
                    CheckResult::Error(format!("exited with {}", out.status))
                } else {
                    let version = (self.parser)(&raw);
                    if version.is_empty() {
                        CheckResult::Error(format!("exited with {}", out.status))
                    } else {
                        CheckResult::Ok(version)
                    }
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => CheckResult::Missing,
            Err(e) => CheckResult::Error(e.to_string()),
        }
    }
}

// ── Parsers ─────────────────────────────────────────────────────────

fn parse_first_line(raw: &str) -> String {
    raw.lines().next().unwrap_or("").trim().to_string()
}

fn parse_git(raw: &str) -> String {
    raw.trim()
        .strip_prefix("git version ")
        .unwrap_or(raw.trim())
        .to_string()
}

fn parse_npm(raw: &str) -> String {
    format!("npm {}", raw.trim())
}

fn parse_pnpm(raw: &str) -> String {
    format!("pnpm {}", raw.trim())
}

fn parse_pip(raw: &str) -> String {
    let line = raw.lines().next().unwrap_or("").trim();
    if let Some(idx) = line.find(" from ")
        && let Some(paren) = line.rfind('(')
    {
        return format!("{} {}", &line[..idx], &line[paren..]);
    }
    line.to_string()
}

fn parse_go(raw: &str) -> String {
    raw.split_whitespace()
        .nth(2)
        .unwrap_or(raw.trim())
        .to_string()
}

fn parse_bash(raw: &str) -> String {
    raw.lines().next().unwrap_or("").trim().to_string()
}

// ── Helpers ─────────────────────────────────────────────────────────

fn run_cmd(cmd: &str, args: &[&str]) -> Option<String> {
    Command::new(cmd)
        .args(args)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
}

fn check_virtualenv(checks: &mut Vec<HealthCheckRecord>, pass: &mut u32, warn: &mut u32) {
    if let Ok(venv) = std::env::var("VIRTUAL_ENV") {
        let short = Path::new(&venv)
            .file_name()
            .unwrap_or_default()
            .to_string_lossy();
        checks.push(HealthCheckRecord {
            name: "venv".into(),
            status: "ok".into(),
            summary: format!("{short} (active)"),
            details: Vec::new(),
        });
        *pass += 1;
        return;
    }

    if let Ok(env) = std::env::var("CONDA_DEFAULT_ENV") {
        checks.push(HealthCheckRecord {
            name: "venv".into(),
            status: "ok".into(),
            summary: format!("conda: {env}"),
            details: Vec::new(),
        });
        *pass += 1;
        return;
    }

    if Path::new(".venv").is_dir() || Path::new("venv").is_dir() {
        checks.push(HealthCheckRecord {
            name: "venv".into(),
            status: "warning".into(),
            summary: "found but not activated".into(),
            details: Vec::new(),
        });
        *warn += 1;
    }
}

fn print_report(report: &HealthReport) {
    let width = report
        .sections
        .iter()
        .flat_map(|section| section.checks.iter())
        .map(|check| check.name.len())
        .max()
        .unwrap_or(0)
        .max(9);

    println!("{}", bold("Environment health check"));
    println!();

    for section in &report.sections {
        if section.checks.is_empty() {
            continue;
        }
        println!("{}", bold(&section.name));
        println!();

        for check in &section.checks {
            let icon = match check.status.as_str() {
                "ok" => green("ok"),
                "warning" => yellow("~~"),
                "error" => red("!!"),
                _ => dim("--"),
            };
            let summary = match check.status.as_str() {
                "warning" => yellow(&check.summary),
                "error" => red(&check.summary),
                _ => dim(&check.summary),
            };

            println!("  {icon} {:<width$}  {summary}", check.name);
            for detail in &check.details {
                println!("    {:<width$}  {}", "", dim(detail));
            }
        }

        println!();
    }

    println!(
        "  {} passed, {} warnings, {} errors",
        green(&report.passed.to_string()),
        yellow(&report.warnings.to_string()),
        if report.errors > 0 {
            red(&report.errors.to_string())
        } else {
            report.errors.to_string()
        },
    );
}

fn detect_privilege() -> String {
    if which_exists("sudo") {
        "sudo".into()
    } else if which_exists("doas") {
        "doas".into()
    } else if which_exists("pkexec") {
        "pkexec".into()
    } else {
        "none".into()
    }
}

fn which_exists(cmd: &str) -> bool {
    Command::new("which")
        .arg(cmd)
        .output()
        .is_ok_and(|o| o.status.success())
}

// ── Cage / container detection ──────────────────────────────────────

enum Cage {
    Docker,
    Podman,
    Lxc,
    Wsl,
    Kubernetes,
    Host,
}

fn cage_name(cage: &Cage) -> &'static str {
    match cage {
        Cage::Docker => "docker",
        Cage::Podman => "podman",
        Cage::Lxc => "lxc",
        Cage::Wsl => "wsl",
        Cage::Kubernetes => "kubernetes",
        Cage::Host => "host",
    }
}

fn detect_cage() -> Cage {
    if Path::new("/var/run/secrets/kubernetes.io").exists() {
        return Cage::Kubernetes;
    }
    if Path::new("/.dockerenv").exists() {
        return Cage::Docker;
    }
    if Path::new("/run/.containerenv").exists() {
        return Cage::Podman;
    }
    if let Ok(cgroup) = std::fs::read_to_string("/proc/1/cgroup") {
        let cg = cgroup.to_lowercase();
        if cg.contains("docker") {
            return Cage::Docker;
        }
        if cg.contains("kubepods") {
            return Cage::Kubernetes;
        }
        if cg.contains("lxc") {
            return Cage::Lxc;
        }
    }
    if let Ok(val) = std::env::var("container") {
        return if val == "podman" {
            Cage::Podman
        } else if val == "lxc" {
            Cage::Lxc
        } else {
            Cage::Docker
        };
    }
    if let Ok(version) = std::fs::read_to_string("/proc/version")
        && (version.contains("microsoft") || version.contains("Microsoft"))
    {
        return Cage::Wsl;
    }
    Cage::Host
}

// ── Available shells ────────────────────────────────────────────────

fn detect_shells() -> Vec<String> {
    let Ok(content) = std::fs::read_to_string("/etc/shells") else {
        return Vec::new();
    };

    let mut shells: Vec<String> = content
        .lines()
        .filter(|l| {
            let l = l.trim();
            !l.is_empty() && !l.starts_with('#') && l.starts_with('/')
        })
        .filter_map(|l| {
            Path::new(l.trim())
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
        })
        .collect();

    shells.sort();
    shells.dedup();
    shells
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plugin::builtin::health_config::{EnvironmentConfig, ToolRequirement};
    use std::collections::BTreeMap;

    fn health_cfg_for_tool(name: &str, requirement: ToolRequirement) -> HealthConfig {
        let mut tools = BTreeMap::new();
        tools.insert(name.to_string(), requirement);
        HealthConfig {
            environment: EnvironmentConfig::default(),
            tools,
            checks: BTreeMap::new(),
        }
    }

    mod compare_versions {
        use super::*;

        #[test]
        fn handles_numeric_segments() {
            assert_eq!(
                compare_versions("1.70.0", "1.9.0"),
                std::cmp::Ordering::Greater
            );
        }

        #[test]
        fn treats_missing_segments_as_zero() {
            assert_eq!(compare_versions("1.2", "1.2.0"), std::cmp::Ordering::Equal);
        }

        #[test]
        fn treats_non_numeric_segments_as_zero() {
            assert_eq!(
                compare_versions("1.beta.3", "1.0.4"),
                std::cmp::Ordering::Less
            );
        }
    }

    mod validate_tool_version {
        use super::*;

        #[test]
        fn returns_none_when_tool_is_not_configured() {
            let cfg = HealthConfig::default();
            assert_eq!(validate_tool_version("rustc", "rustc 1.85.0", &cfg), None);
        }

        #[test]
        fn rejects_exact_version_mismatch() {
            let cfg = health_cfg_for_tool(
                "rustc",
                ToolRequirement {
                    required: true,
                    min_version: None,
                    exact_version: Some("1.85.0".into()),
                    command: None,
                    version_args: None,
                    url: None,
                    install: None,
                    latest_cmd: None,
                    latest_args: None,
                },
            );

            assert_eq!(
                validate_tool_version("rustc", "rustc 1.84.0", &cfg),
                Some("expected 1.85.0, got 1.84.0".into())
            );
        }

        #[test]
        fn rejects_lower_than_minimum_version() {
            let cfg = health_cfg_for_tool(
                "rustc",
                ToolRequirement {
                    required: true,
                    min_version: Some("1.85.0".into()),
                    exact_version: None,
                    command: None,
                    version_args: None,
                    url: None,
                    install: None,
                    latest_cmd: None,
                    latest_args: None,
                },
            );

            assert_eq!(
                validate_tool_version("rustc", "rustc 1.84.0", &cfg),
                Some("minimum 1.85.0, got 1.84.0".into())
            );
        }

        #[test]
        fn accepts_satisfied_constraints() {
            let cfg = health_cfg_for_tool(
                "rustc",
                ToolRequirement {
                    required: true,
                    min_version: Some("1.84.0".into()),
                    exact_version: None,
                    command: None,
                    version_args: None,
                    url: None,
                    install: None,
                    latest_cmd: None,
                    latest_args: None,
                },
            );

            assert_eq!(validate_tool_version("rustc", "rustc 1.85.1", &cfg), None);
        }
    }

    mod parsers {
        use super::*;

        #[test]
        fn extract_version_number_finds_first_semver_like_word() {
            assert_eq!(
                extract_version_number("cargo 1.85.1 (d73d2caf9 2024-12-31)"),
                "1.85.1"
            );
        }

        #[test]
        fn parse_helpers_return_expected_strings() {
            assert_eq!(parse_first_line("first\nsecond\n"), "first");
            assert_eq!(parse_git("git version 2.49.0"), "2.49.0");
            assert_eq!(parse_npm("10.9.0"), "npm 10.9.0");
            assert_eq!(parse_pnpm("9.1.0"), "pnpm 9.1.0");
            assert_eq!(
                parse_pip("pip 24.0 from /tmp/site-packages/pip (python 3.12)"),
                "pip 24.0 (python 3.12)"
            );
            assert_eq!(parse_go("go version go1.22.1 linux/amd64"), "go1.22.1");
            assert_eq!(parse_bash("GNU bash, version 5.2.0"), "GNU bash, version 5.2.0");
            assert_eq!(cage_name(&Cage::Host), "host");
        }
    }

    mod check_execute {
        use super::*;

        #[test]
        fn returns_ok_from_stdout_on_success() {
            let check = Check::tool("/bin/sh", &["-c", "echo 1.2.3"], parse_first_line)
                .display_name("tool");

            match check.execute() {
                CheckResult::Ok(version) => assert_eq!(version, "1.2.3"),
                _ => panic!("expected success"),
            }
        }

        #[test]
        fn falls_back_to_stderr_when_stdout_is_empty() {
            let check = Check::tool("/bin/sh", &["-c", "echo 4.5.6 1>&2"], parse_first_line)
                .display_name("tool");

            match check.execute() {
                CheckResult::Ok(version) => assert_eq!(version, "4.5.6"),
                _ => panic!("expected stderr-derived success"),
            }
        }

        #[test]
        fn returns_parsed_stderr_output_for_non_zero_exit() {
            let check = Check::tool(
                "/bin/sh",
                &["-c", "echo tool 7.8.9 1>&2; exit 2"],
                parse_first_line,
            )
            .display_name("tool");

            match check.execute() {
                CheckResult::Ok(version) => assert_eq!(version, "tool 7.8.9"),
                _ => panic!("expected parsed stderr output"),
            }
        }

        #[test]
        fn returns_error_when_non_zero_exit_has_no_parseable_output() {
            let check =
                Check::tool("/bin/sh", &["-c", "exit 3"], parse_first_line).display_name("tool");

            match check.execute() {
                CheckResult::Error(message) => assert!(!message.is_empty()),
                _ => panic!("expected error"),
            }
        }

        #[test]
        fn returns_missing_when_command_does_not_exist() {
            let check = Check::tool("definitely-not-a-command", &[], parse_first_line)
                .display_name("tool");

            match check.execute() {
                CheckResult::Missing => {}
                _ => panic!("expected missing command"),
            }
        }
    }
}
